<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use kartik\select2\Select2;
use yii\widgets\Pjax;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use app\models\Rubro;
use app\models\Municipio;

/* @var $this yii\web\View */
/* @var $searchModel app\models\DireccionSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Direccion';
$this->params['breadcrumbs'][] = $this->title;

$municipio_id = intval($searchModel['municipio_id']);
if($municipio_id!=NULL)
{
    $parroquia = ArrayHelper::map(\app\models\Parroquia::find()->where(['municipio_id'=>$municipio_id])->orderBy('parroquia ASC')->asArray()->all(),'id','parroquia');
}
else
{
    $parroquia = ArrayHelper::map(\app\models\Parroquia::find()->orderBy('parroquia ASC')->asArray()->all(),'id','parroquia');
}

$parroquia_id =intval( $searchModel['parroquia_id']);
if($parroquia_id!=NULL)
{
$sector = ArrayHelper::map(\app\models\Sector::find()->where(['parroquia_id'=>$parroquia_id])->orderBy('sector ASC')->asArray()->all(),'id','sector');
}
else
{
$sector = ArrayHelper::map(\app\models\Sector::find()->orderBy('sector ASC')->asArray()->all(),'id','sector');
}
?>
<div class="direccion-index">

<?php Pjax::begin([
    'enablePushState'=>false,
]);?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'autoXlFormat'=>true,
        'responsive'=>true,
        'hover'=>true,
        'bootstrap'=>true,
        'bordered'=>true,
        'condensed'=>true,
        'responsive'=>true,
        'responsiveWrap'=>true,
        'floatHeader'=>false,
        'resizableColumns'=>false,
        'toolbar'=>[
            '{export}',
            '{toggleData}'
        ],
        'panel' => [
            'heading'=>'<h3 class="panel-title"> Direccion Comerciantes </h3>',
            'type'=>'primary',
            'before'=>Html::a('Registrar Comerciante :: <span class="glyphicon glyphicon-user"></span>', ['/comerciante/create'], ['class' => 'btn btn-success']),
            'footer'=>false,
        ],
        'export'=>[
            'showConfirmAlert'=>false,
        ],
        'exportConfig'=>[
       
            GridView::PDF => [
               // 'label' => Yii::t('kvgrid', 'PDF'),
                //'icon' => $isFa ? 'file-pdf-o' : 'floppy-disk',
                'iconOptions' => ['class' => 'text-danger'],
                'showHeader' => true,
                'showPageSummary' => false,
                'showFooter' => false,
                'showCaption' => true,
                //'defaultFontSize'=>16,
                'filename' => 'Registro de Comercinates Informales',
                //'alertMsg' => Yii::t('kvgrid', 'The PDF export file will be generated for download.'),
                'options' => ['title' => 'PDF'],
                'mime' => 'application/pdf',
                'config' => [
                    'mode' => 'utf-8',
                    'format' => 'Letter',
                    'orientation'=>'L',
                    'destination' => 'D',
                    'marginTop' => 5,
                    'marginBottom' => 5,
                    'cssInline' => '.kv-wrap{padding:20px;}' .
                        '.kv-align-center{text-align:center;}' .
                        '.kv-align-left{text-align:left;}' .
                        '.kv-align-right{text-align:right;}' .
                        '.kv-align-top{vertical-align:top!important;}' .
                        '.kv-align-bottom{vertical-align:bottom!important;}' .
                        '.kv-align-middle{vertical-align:middle!important;}' .
                        '.kv-table-footer{border-top:4px double #ddd;font-weight: bold;}' .
                        '.kv-table-caption{font-size:1.5em;padding:4px;border:1px solid #ddd;border-bottom:none;}',
                    'methods' => [
                        'SetHeader' => [
                           ['odd' => '', 'even' => '']
                        ],
                        'SetFooter' =>('Alcaldia de Heres, Desarrollo Socio Productivo, Unidad de Economia Popular. pagina  {PAGENO}'),
                    ],
                    'options' => [
                        //'title' => $title,
                       // 'subject' => Yii::t('kvgrid', 'PDF export generated by kartik-v/yii2-grid extension'),
                        //'keywords' => Yii::t('kvgrid', 'krajee, grid, export, yii2-grid, pdf')
                    ],
                    'contentBefore'=>'',
                    'contentAfter'=>''
                ]
            ],

            GridView::EXCEL => [
                //'label' => Yii::t('kvgrid', 'Excel'),
                //'icon' => $isFa ? 'file-excel-o' : 'floppy-remove',
                'iconOptions' => ['class' => 'text-success'],
                'showHeader' => true,
               // 'showPageSummary' => true,
                'showFooter' => true,
                'showCaption' => true,
                'filename' => 'Reportes de Comerciantes Informales',
                //'alertMsg' => Yii::t('kvgrid', 'The EXCEL export file will be generated for download.'),
                //'options' => ['title' => Yii::t('kvgrid', 'Microsoft Excel 95+')],
                'mime' => 'application/vnd.ms-excel',
                'config' => [
                    'worksheet' =>  'ExportWorksheet',
                ]
            ],
        ],
        'caption'=>'Registro de Direcciones de Comerciantes',
        'captionOptions'=>['class'=>'text-center text-success lead'],
        'rowOptions'=>['style'=>'font-size:smaller'],
        'headerRowOptions'=>['style'=>'font-size:smaller'],
        'columns' => [
            [
              'class' => 'kartik\grid\SerialColumn',
              'header'=>'N',
              'headerOptions'=>['class'=>'text-primary text-center','style'=>'font-size:12px'],
              'contentOptions'=>['style'=>'font-size:10px'],
              
            ],
            [
                'label'=>'Municipio',
                'attribute'=>'municipio_id',
                'value'=>'municipio.municipio',
                'filter'=>Select2::widget([
                    'model'=>$searchModel,
                    'attribute'=>'municipio_id',
                    'data'=>ArrayHelper::map(Municipio::find()->select(['id','municipio'])->orderBy('municipio ASC')->asArray()->all(),'id','municipio'),
                    'language'=>'es',
                    'options'=>[
                    'placeholder'=>'Municipio'],
                    'pluginOptions' => [
                              'allowClear' => true
                      ],
                  ]),
                'headerOptions'=>['class'=>'text-primary','style'=>'font-size:12px',],
                'contentOptions'=>['style'=>'font-size:10px'],
            ],
            [
                'label'=>'Parroquia',
                'attribute'=>'parroquia_id',
                'value'=>'parroquia.parroquia',
                'filter'=>Select2::widget([
                    'model'=>$searchModel,
                    'attribute'=>'parroquia_id',
                    'data'=>$parroquia,
                    'language'=>'es',
                    'options'=>[
                    'placeholder'=>'Parroquia'],
                    'pluginOptions' => [
                              'allowClear' => true
                      ],
                  ]),
                'headerOptions'=>['class'=>'text-primary','style'=>'font-size:12px',],
                'contentOptions'=>['style'=>'font-size:10px'],
            ],
            [
                'label'=>'Sector',
                'attribute'=>'sector_id',
                'value'=>'sector.sector',
                'filter'=>Select2::widget([
                    'model'=>$searchModel,
                    'attribute'=>'sector_id',
                    'data'=>$sector,
                    'language'=>'es',
                    'options'=>[
                    'placeholder'=>'Sector'],
                    'pluginOptions' => [
                              'allowClear' => true
                      ],
                  ]),
                  'headerOptions'=>['class'=>'text-primary','style'=>'font-size:12px',],
                  'contentOptions'=>['style'=>'font-size:10px'],
            ],
            [
                'label'=>'Direccion',
                'attribute'=>'direccion',
                'value'=>'direccion',
                'headerOptions'=>['class'=>'text-primary','style'=>'font-size:12px',],
                'contentOptions'=>['style'=>'font-size:10px'],

            ],
            [
                'label'=>'Cedula',
                'attribute'=>'cedula',
                'value'=>'comerciante.cedula',
                'headerOptions'=>['class'=>'text-primary','style'=>'font-size:12px',],
                'contentOptions'=>['style'=>'font-size:10px'],
            ],
            [
                'label'=>'Telefono',
                'attribute'=>'telefono',
                'value'=>'comerciante.telefono',
                'headerOptions'=>['class'=>'text-primary','style'=>'font-size:12px',],
                'contentOptions'=>['style'=>'font-size:10px'],
            ],
            [
                'label'=>'Comerciante',
                'attribute'=>'comerciante',
                'value'=>'comerciante.nombres_y_apellidos',
                'headerOptions'=>['class'=>'text-primary','style'=>'font-size:12px',],
                'contentOptions'=>['style'=>'font-size:10px'],
            ],
            [
                'label'=>'Rubro',
                'attribute'=>'rubro',
                'value'=>'comerciante.rubro.rubro',
                'headerOptions'=>['class'=>'text-primary','style'=>'font-size:12px',],
                'contentOptions'=>['style'=>'font-size:10px'],
                 'filter'=> Select2::widget([
                 'model'=>$searchModel,
                 'attribute'=>'rubro',
                 'data'=>ArrayHelper::map(Rubro::find()->orderBy('rubro ASC')->asArray()->all(),'id','rubro'),
                 'language'=>'es',
                 'options'=>[
                 'placeholder'=>'Rubro'],
                 'pluginOptions' => [
                           'allowClear' => true
                   ],
               ]),
            ],

            [
                'class' => 'kartik\grid\ActionColumn',
                'hiddenFromExport'=>true,
                'header'=>'  Acciones  ',
                'headerOptions'=>['class'=>'text-center text-primary','style'=>'width: 113px;'],
                'contentOptions'=>['class'=>'center-block text-center','style'=>'width: 113px;'],
                'template'=>'{view} {update} {permiso} {historico} {delete}',
                'buttons'=>
                [
                     'view'=>function($url,$model)
                    {
                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>',$url,['class'=>'text-center text-success','title'=>'Ver']);
                    },
                    'update'=>function($url,$model)
                    {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>',$url,['class'=>'text-center','title'=>'Editar']);
                    },
                    'delete'=>function($url,$model)
                    {
                        if(Yii::$app->user->identity->type_user==0){
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>',$url,['class'=>'text-center text-danger','title'=>'Eliminar','data-pjax'=>0,'data-confirm'=>'¿Desea eliminar este comerciante ?>','data-method'=>'post']);
                        }
                    },
                    'permiso'=>function($url,$model)
                    {
                        return Html::a('<span class="glyphicon glyphicon-list-alt permiso"></span>',$url,['class'=>'text-center text-warning','title'=>'Generar Permiso']);
                    },
                    'historico'=>function($url,$model)
                    {
                        if(Yii::$app->user->identity->type_user==0){
                        return Html::a('<span class="glyphicon glyphicon-book historico"></span>',$url,['class'=>'text-center text-info','title'=>'ver historico']);
                        }
                    }
                ],
                'urlCreator'=>function($action, $model, $key, $index)
                {
                    if($action=='permiso')
                    {
    
                       return Url::to(['permiso','id'=>$model->comerciante_id]);
                    }
                    else if($action=='view')
                    {
                        return Url::to(['/comerciante/view','id'=>$model->comerciante_id]);
                    }
                    else if($action=='update')
                    {
                        return Url::to(['/comerciante/update','id'=>$model->comerciante_id]);
                    }
                    else if($action=='historico')
                    {
                        return Url::to(['/comerciante/historico','id'=>$model->comerciante_id]);
                    }
                    else if($action=='delete')
                    {
                        return Url::to(['/comerciante/delete','id'=>$model->comerciante_id]);
                    }
                }
               
                
            ],
        ],
    ]); ?>
    <?php Pjax::end();?>
</div>
