<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use kartik\select2\Select2;
use yii\widgets\Pjax;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use app\models\Comerciante;
use app\models\Rubro;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ComercianteSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Comerciantes';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="comerciante-index">

    <?php //echo $this->render('_search', ['model' => $searchModel]); ?>

    <?php Pjax::begin(['enablePushState'=>false]);?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'autoXlFormat'=>true,
        'responsive'=>true,
        'hover'=>true,
        'bootstrap'=>true,
        'bordered'=>true,
        'condensed'=>true,
        'responsive'=>true,
        'responsiveWrap'=>true,
        'floatHeader'=>false,
        'resizableColumns'=>false,
        'toolbar'=>[
            '{export}',
            '{toggleData}'
        ],
        'panel' => [
            'heading'=>'<h3 class="panel-title">Datos Comerciantes </h3>',
            'type'=>'primary',
            'before'=>Html::a('Registrar Comerciante :: <span class="glyphicon glyphicon-user"></span>', ['create'], ['class' => 'btn btn-success']),
            'footer'=>false,
        ],
        'export'=>[
            'showConfirmAlert'=>false,
        ],
        'exportConfig'=>[
       
            GridView::PDF => [
               // 'label' => Yii::t('kvgrid', 'PDF'),
                //'icon' => $isFa ? 'file-pdf-o' : 'floppy-disk',
                'iconOptions' => ['class' => 'text-danger'],
                'showHeader' => true,
                'showPageSummary' => false,
                'showFooter' => false,
                'showCaption' => true,
                //'defaultFontSize'=>16,
                'filename' => 'Registro de Comercinates Informales',
                //'alertMsg' => Yii::t('kvgrid', 'The PDF export file will be generated for download.'),
                'options' => ['title' => 'PDF'],
                'mime' => 'application/pdf',
                'config' => [
                    'mode' => 'utf-8',
                    'format' => 'Letter',
                    'orientation'=>'L',
                    'destination' => 'D',
                    'marginTop' => 5,
                    'marginBottom' => 5,
                    'cssInline' => '.kv-wrap{padding:20px;}' .
                        '.kv-align-center{text-align:center;}' .
                        '.kv-align-left{text-align:left;}' .
                        '.kv-align-right{text-align:right;}' .
                        '.kv-align-top{vertical-align:top!important;}' .
                        '.kv-align-bottom{vertical-align:bottom!important;}' .
                        '.kv-align-middle{vertical-align:middle!important;}' .
                        '.kv-table-footer{border-top:4px double #ddd;font-weight: bold;}' .
                        '.kv-table-caption{font-size:1.5em;padding:4px;border:1px solid #ddd;border-bottom:none;}',
                    'methods' => [
                        'SetHeader' => [
                           ['odd' => '', 'even' => '']
                        ],
                        'SetFooter' =>('Alcaldia de Heres, Desarrollo Socio Productivo, Unidad de Economia Popular. pagina  {PAGENO}'),
                    ],
                    'options' => [
                        //'title' => $title,
                       // 'subject' => Yii::t('kvgrid', 'PDF export generated by kartik-v/yii2-grid extension'),
                        //'keywords' => Yii::t('kvgrid', 'krajee, grid, export, yii2-grid, pdf')
                    ],
                    'contentBefore'=>'',
                    'contentAfter'=>''
                ]
            ],

            GridView::EXCEL => [
                //'label' => Yii::t('kvgrid', 'Excel'),
                //'icon' => $isFa ? 'file-excel-o' : 'floppy-remove',
                'iconOptions' => ['class' => 'text-success'],
                'showHeader' => true,
               // 'showPageSummary' => true,
                'showFooter' => true,
                'showCaption' => true,
                'filename' => 'Reportes de Comerciantes Informales',
                //'alertMsg' => Yii::t('kvgrid', 'The EXCEL export file will be generated for download.'),
                //'options' => ['title' => Yii::t('kvgrid', 'Microsoft Excel 95+')],
                'mime' => 'application/vnd.ms-excel',
                'config' => [
                    'worksheet' =>  'ExportWorksheet',
                ]
            ],
        ],
        'caption'=>'Registro de comerciantes',
        'captionOptions'=>['class'=>'text-center text-success lead'],
        'rowOptions'=>['style'=>'font-size:smaller'],
        'headerRowOptions'=>['style'=>'font-size:smaller'],
        'columns' => [
            [
              'class' => 'kartik\grid\SerialColumn',
              'header'=>'N',
              'headerOptions'=>['class'=>'text-primary text-center','style'=>'font-size:12px'],
              'contentOptions'=>['style'=>'font-size:10px'],
              
            ],
            [
                'label'=>'Cedula',
                'attribute'=>'cedula',
                'value'=>'cedula',
                'headerOptions'=>['class'=>'text-primary','style'=>'font-size:12px',],
                'contentOptions'=>['style'=>'font-size:10px'],
            ],
            [
                'label'=>'Comerciante',
                'attribute'=>'nombres_y_apellidos',
                'value'=>'nombres_y_apellidos',
                'headerOptions'=>['class'=>'text-primary','style'=>'font-size:12px',],
                'contentOptions'=>['style'=>'font-size:10px'],
            ],
            [
                'label'=>'Telefono',
                'attribute'=>'telefono',
                'value'=>'telefono',
                'headerOptions'=>['class'=>'text-primary','style'=>'font-size:12px',],
                'contentOptions'=>['style'=>'font-size:10px'],
            ],
            [
                'label'=>'Sexo',
                'attribute'=>'sexo',
                'value'=>'sexo',
                'filter'=>Select2::widget([
                    'model'=>$searchModel,
                    'attribute'=>'sexo',
                    'data'=>ArrayHelper::map(Comerciante::find()->select('sexo')->orderBy('sexo ASC')->asArray()->all(),'sexo','sexo'),
                    'language'=>'es',
                    'options'=>[
                    'placeholder'=>'Sexo'],
                    'pluginOptions' => [
                              'allowClear' => true
                      ],
                  ]),
                  'headerOptions'=>['class'=>'text-primary','style'=>'font-size:12px',],
                  'contentOptions'=>['style'=>'font-size:10px'],
            ],
            [
                'label'=>'Estado Civil',
                'attribute'=>'estado_civil',
                'value'=>'estado_civil',
                'filter'=>Select2::widget([
                    'model'=>$searchModel,
                    'attribute'=>'estado_civil',
                    'data'=>ArrayHelper::map(Comerciante::find()->select('estado_civil')->orderBy('estado_civil ASC')->asArray()->all(),'estado_civil','estado_civil'),
                    'language'=>'es',
                    'options'=>[
                    'placeholder'=>'Estado civil'],
                    'pluginOptions' => [
                              'allowClear' => true
                      ],
                  ]),
                  'headerOptions'=>['class'=>'text-primary','style'=>'font-size:12px',],
                  'contentOptions'=>['style'=>'font-size:10px'],
            ],
            [
                'label'=>'Tipo',
                'attribute'=>'tipo',
                'value'=>'tipo',
                'filter'=>Select2::widget([
                    'model'=>$searchModel,
                    'attribute'=>'tipo',
                    'data'=>ArrayHelper::map(Comerciante::find()->select('tipo')->orderBy('tipo ASC')->asArray()->all(),'tipo','tipo'),
                    'language'=>'es',
                    'options'=>[
                    'placeholder'=>'Tipo'],
                    'pluginOptions' => [
                              'allowClear' => true
                      ],
                  ]),
                  'headerOptions'=>['class'=>'text-primary','style'=>'font-size:12px',],
                  'contentOptions'=>['style'=>'font-size:10px'],
            ],
            [
                'label'=>'Rubro',
                'attribute'=>'rubro_id',
                'value'=>'rubro.rubro',
                'headerOptions'=>['class'=>'text-primary','style'=>'font-size:12px',],
                'contentOptions'=>['style'=>'font-size:10px'],
                 'filter'=> Select2::widget([
                 'model'=>$searchModel,
                 'attribute'=>'rubro_id',
                 'data'=>ArrayHelper::map(Rubro::find()->orderBy('rubro ASC')->asArray()->all(),'id','rubro'),
                 'language'=>'es',
                 'options'=>[
                 'placeholder'=>'Rubro'],
                 'pluginOptions' => [
                           'allowClear' => true
                   ],
               ]),
            ],

            [
                'class' => 'kartik\grid\ActionColumn',
                'hiddenFromExport'=>true,
                'header'=>'  Acciones  ',
                'template'=>'{view} {update} {permiso} {historico} {delete}',
                'buttons'=>
                [
                     'view'=>function($url,$model)
                    {
                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>',$url,['class'=>'text-center text-success','title'=>'Ver']);
                    },
                    'update'=>function($url,$model)
                    {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>',$url,['class'=>'text-center','title'=>'Editar']);
                    },
                    'delete'=>function($url,$model)
                    {
                        if(Yii::$app->user->identity->type_user==0){
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>',$url,['class'=>'text-center text-danger','title'=>'Eliminar','data-pjax'=>0,'data-confirm'=>'¿Desea eliminar este comerciante ?>','data-method'=>'post']);
                        }
                    },
                    'permiso'=>function($url,$model)
                    {
                        return Html::a('<span class="glyphicon glyphicon-list-alt permiso"></span>',$url,['class'=>'text-center text-warning','title'=>'Generar Permiso']);
                    },
                    'historico'=>function($url,$model)
                    {
                        if(Yii::$app->user->identity->type_user==0){
                        return Html::a('<span class="glyphicon glyphicon-book historico"></span>',$url,['class'=>'text-center text-info','title'=>'ver historico']);
                        }
                    }
                ],
                'headerOptions'=>['class'=>'text-center text-primary','style'=>'width: 113px;'],
                'contentOptions'=>['class'=>'center-block text-center','style'=>'width: 113px;'],
                
            ],
        ],
    ]); ?>
    <?php Pjax::end();?>

    
</div>
